# Generated by Django 5.2.5 on 2025-08-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buyer',
        ),
    ]
