# Generated by Django 5.2.5 on 2025-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_review_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
