# Generated by Django 5.2.5 on 2025-08-13 07:01

import django.db.models.deletion
import services.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serviceimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='seller',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service/images/', validators=[services.validators.validate_file_size]),
        ),
    ]
