# Generated by Django 5.2.5 on 2025-08-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceimage_seller_alter_serviceimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='seller',
        ),
    ]
