# Generated by Django 5.2.5 on 2025-08-12 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In_progress', 'In_progress'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirements', models.TextField(blank=True)),
            ],
        ),
    ]
