# Generated by Django 5.2.5 on 2025-08-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_created_at_order_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='update_at',
        ),
    ]
