# Generated by Django 5.2.5 on 2025-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
